# Generated by Django 3.0.3 on 2020-07-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200703_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(max_length=100),
        ),
    ]
