# Generated by Django 3.0.3 on 2020-07-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
