# Generated by Django 3.0.3 on 2020-07-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='data',
            new_name='date',
        ),
    ]
